apiVersion: v1
kind: Secret
metadata:
  name: {{ include "librechat.fullname" . }}-secret
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}