apiVersion: v1
kind: Service
metadata:
  name: {{ include "librechat.fullname" . }}-meilisearch
  labels:
    {{- include "librechat.labels" . | nindent 4 }}-meilisearch
    app: {{ include "librechat.fullname" . }}-meilisearch
spec:
  type: {{ .Values.meilisearch.service.type }}
  ports:
    - port: {{ .Values.meilisearch.service.port }}
      targetPort: {{ .Values.meilisearch.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "librechat.selectorLabels" . | nindent 4 }}
    app: {{ include "librechat.fullname" . }}-meilisearch
