apiVersion: v1
kind: Service
metadata:
  name: {{ include "librechat.fullname" . }}-vectordb
  labels:
    {{- include "librechat.labels" . | nindent 4 }}-vectordb
    app: {{ include "librechat.fullname" . }}-vectordb
spec:
  type: {{ .Values.vectordb.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.vectordb.service.port | default 5432 }}
      targetPort: {{ .Values.vectordb.service.port | default 5432 }}
      protocol: TCP
      name: postgresql
  selector:
    {{- include "librechat.selectorLabels" . | nindent 4 }}
    app: {{ include "librechat.fullname" . }}-vectordb
